"""
Build nemo-v10-ES-EGGROLL.ipynb programmatically.

Implements vanilla Evolution Strategies (ES) fine-tuning of LoRA adapters on
Nemotron-3-Nano-30B-A3B per arXiv:2509.24372, with hooks toward EGGROLL-style
low-rank perturbations (arXiv:2511.16652). Reuses the v9-1 GRPO multi-component
reward and the v7-5 Kaggle setup boilerplate.
"""
from __future__ import annotations

import json
from pathlib import Path

NB_PATH = Path(__file__).parent / "nemo-v10-ES-EGGROLL.ipynb"


def md(text: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": text.splitlines(keepends=True),
    }


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


# =============================================================================
# Cells
# =============================================================================

cells = []

cells.append(md(
    "# Nemotron-3-Nano-30B — Evolution Strategies LoRA Fine-Tuning (v10)\n"
    "\n"
    "Backprop-free LoRA fine-tuning via Evolution Strategies (ES).\n"
    "\n"
    "**Papers**\n"
    "* arXiv:2509.24372 — *Evolution Strategies at Scale: LLM Fine-Tuning Beyond Reinforcement Learning*\n"
    "* arXiv:2511.16652 — *Evolution Strategies at Hyperscale (EGGROLL)*\n"
    "\n"
    "**Why ES for Nemotron-Kaggle**\n"
    "* No gradients / no optimizer state → fits 30B MoE in Kaggle VRAM more comfortably than GRPO\n"
    "* Reward is non-differentiable (`\\boxed{}` match) — ES handles natively\n"
    "* LoRA's low-rank structure composes with EGGROLL low-rank noise (hook included, vanilla is default)\n"
    "* Beats GRPO on countdown / GSM8K in the EGGROLL paper\n"
    "\n"
    "**Tradeoffs**\n"
    "* Population size capped by VRAM (≈ 4–8 here vs paper's 2²⁰)\n"
    "* Statistical signal weaker per step → use centered-rank normalization + antithetic pairs\n"
    "* Best used as **post-SFT polish stage** (`INIT_FROM_SFT_ADAPTER=1`), not from cold base\n"
))

cells.append(md("## Mode Selection"))

cells.append(code(
    'import os, sys\n'
    'os.environ["PYTHONIOENCODING"] = "utf-8"\n'
    'os.environ["UNSLOTH_COMPILE_DISABLE"] = "1"\n'
    'os.environ["TORCH_COMPILE_DISABLE"] = "1"\n'
    'os.environ["TORCHINDUCTOR_DISABLE"] = "1"\n'
    'if hasattr(sys.stdout, "reconfigure"):\n'
    '    sys.stdout.reconfigure(encoding="utf-8", errors="strict")\n'
    'if hasattr(sys.stderr, "reconfigure"):\n'
    '    sys.stderr.reconfigure(encoding="utf-8", errors="strict")\n'
    '\n'
    '# Mode A: Train LoRA via ES on Kaggle GPU\n'
    'TRAIN_ON_KAGGLE = 1\n'
    '\n'
    '# Mode B: Use a pre-trained LoRA dataset and just package it\n'
    'USE_PRETRAINED = 0\n'
    '\n'
    'assert (TRAIN_ON_KAGGLE + USE_PRETRAINED) == 1, \\\n'
    '    "Set exactly one of TRAIN_ON_KAGGLE / USE_PRETRAINED to 1."\n'
    '\n'
    '# -----------------------------------------------------------------------\n'
    '# Init source for ES:\n'
    '#   0 = start ES on a fresh LoRA (kaiming A, zero B) on top of base model\n'
    '#   1 = warm-start ES from an existing SFT LoRA adapter (recommended)\n'
    '# -----------------------------------------------------------------------\n'
    'INIT_FROM_SFT_ADAPTER = 1\n'
    '\n'
    '# Path to existing SFT adapter (only used when INIT_FROM_SFT_ADAPTER=1).\n'
    '# Should contain adapter_config.json + adapter_model.safetensors.\n'
    'SFT_ADAPTER_PATH = "/kaggle/input/datasets/konbu17/nemotron-sft-lora-cot-selection"\n'
    '\n'
    'PRETRAINED_ADAPTER_DATASET_PATH = "/kaggle/input/datasets/konbu17/nemotron-sft-lora-cot-selection"\n'
    'BASE_MODEL_NAME = "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16"\n'
    '\n'
    'print({\n'
    '    "TRAIN_ON_KAGGLE": TRAIN_ON_KAGGLE,\n'
    '    "USE_PRETRAINED": USE_PRETRAINED,\n'
    '    "INIT_FROM_SFT_ADAPTER": INIT_FROM_SFT_ADAPTER,\n'
    '    "SFT_ADAPTER_PATH": SFT_ADAPTER_PATH,\n'
    '})\n'
))

cells.append(md("## Setup & Model Loading"))

cells.append(code(
    'import os, glob, sys, subprocess, site\n'
    '\n'
    'candidates = glob.glob("/kaggle/input/**/*triton*.whl", recursive=True)\n'
    'print("Found Triton wheels:", candidates)\n'
    '\n'
    'if not candidates:\n'
    '    raise FileNotFoundError("No Triton wheel found under /kaggle/input")\n'
    'wheel = candidates[0]\n'
    '\n'
    'target = "/kaggle/working/pydeps"\n'
    'os.makedirs(target, exist_ok=True)\n'
    '\n'
    'subprocess.run(\n'
    '    [\n'
    '        sys.executable, "-m", "pip", "install",\n'
    '        "--no-deps",\n'
    '        "--target", target,\n'
    '        "--upgrade",\n'
    '        "--ignore-installed",\n'
    '        wheel,\n'
    '    ],\n'
    '    check=True,\n'
    ')\n'
    '\n'
    'if target not in sys.path:\n'
    '    sys.path.insert(0, target)\n'
    '\n'
    'site.addsitedir(target)\n'
    '\n'
    'print("Custom target added:", target)\n'
    '\n'
    'import importlib.util\n'
    'print("triton spec:", importlib.util.find_spec("triton"))\n'
))

cells.append(code(
    'if TRAIN_ON_KAGGLE:\n'
    '    import sys, os, shutil, stat\n'
    '\n'
    "    sys.path.insert(0, '/kaggle/usr/lib/notebooks/ryanholbrook/nvidia_utility_script')\n"
    '\n'
    "    ptxas_src = '/kaggle/usr/lib/notebooks/ryanholbrook/nvidia_utility_script/triton/backends/nvidia/bin/ptxas-blackwell'\n"
    "    ptxas_dst = '/tmp/ptxas-blackwell'\n"
    '    if os.path.exists(ptxas_src) and not os.path.exists(ptxas_dst):\n'
    '        shutil.copy2(ptxas_src, ptxas_dst)\n'
    '        os.chmod(ptxas_dst, os.stat(ptxas_dst).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)\n'
    '\n'
    '        src_bin = os.path.dirname(ptxas_src)\n'
    "        dst_bin = '/tmp/triton_nvidia_bin'\n"
    '        shutil.copytree(src_bin, dst_bin, dirs_exist_ok=True)\n'
    '        for f in os.listdir(dst_bin):\n'
    '            fp = os.path.join(dst_bin, f)\n'
    '            if os.path.isfile(fp):\n'
    '                os.chmod(fp, os.stat(fp).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)\n'
    '\n'
    "        os.environ['TRITON_PTXAS_BLACKWELL_PATH'] = ptxas_dst\n"
    '\n'
    '        import triton.backends.nvidia as nv_backend\n'
    "        nv_backend.__file__ = os.path.join(dst_bin, '..', '__init__.py')\n"
    "        os.environ['TRITON_PTXAS_PATH'] = ptxas_dst\n"
    '\n'
    '    import triton.backends.nvidia.compiler as nv_compiler\n'
    "    nv_compiler.get_ptxas_version = lambda arch: '12.0'\n"
    '\n'
    "    print('Training environment fixes applied.')\n"
    'else:\n'
    '    print("USE_PRETRAINED=1: skipping Triton / ptxas environment fixes.")\n'
))

cells.append(code(
    'if TRAIN_ON_KAGGLE:\n'
    '    import glob\n'
    '    import os\n'
    '    import subprocess\n'
    '    import sys\n'
    '\n'
    '    def recursive_wheels(pattern: str):\n'
    '        return sorted(glob.glob(f"/kaggle/input/**/{pattern}", recursive=True))\n'
    '\n'
    '    packages_dir = "/kaggle/input/datasets/mayukh18/nemotron-packages/packages"\n'
    '    all_mamba = recursive_wheels("mamba_ssm-*.whl")\n'
    '    all_causal = recursive_wheels("causal*conv1d*.whl")\n'
    '\n'
    '    print("Found mamba wheels:", all_mamba)\n'
    '    print("Found causal-conv1d wheels:", all_causal)\n'
    '\n'
    '    import torch\n'
    '    print("Python:", sys.version)\n'
    '    print("Torch:", torch.__version__)\n'
    '    print("CUDA available:", torch.cuda.is_available())\n'
    '    print("Torch CUDA:", torch.version.cuda)\n'
    '\n'
    '    if not torch.cuda.is_available():\n'
    '        raise RuntimeError("TRAIN_ON_KAGGLE=1 requires a GPU runtime.")\n'
    '\n'
    '    if not os.path.isdir(packages_dir):\n'
    '        raise FileNotFoundError(f"Offline wheel directory not found: {packages_dir}")\n'
    '\n'
    '    subprocess.run(\n'
    '        [\n'
    '            sys.executable, "-m", "pip", "install", "-q",\n'
    '            "--no-index", "--find-links", packages_dir,\n'
    '            "unsloth", "trl", "peft", "transformers", "datasets", "accelerate", "bitsandbytes",\n'
    '        ],\n'
    '        check=True,\n'
    '    )\n'
    '\n'
    '    def pick_last(wheels):\n'
    '        return wheels[-1] if wheels else None\n'
    '\n'
    '    causal_wheel = pick_last(all_causal)\n'
    '    mamba_wheel = pick_last(all_mamba)\n'
    '    print("Selected causal wheel:", causal_wheel)\n'
    '    print("Selected mamba wheel:", mamba_wheel)\n'
    '\n'
    '    if causal_wheel:\n'
    '        subprocess.run([sys.executable, "-m", "pip", "install", "--no-index", "--no-deps", causal_wheel], check=True)\n'
    '    if mamba_wheel:\n'
    '        subprocess.run([sys.executable, "-m", "pip", "install", "--no-index", "--no-deps", mamba_wheel], check=True)\n'
    '    else:\n'
    '        raise FileNotFoundError("Could not find a compatible mamba_ssm wheel under /kaggle/input.")\n'
    '\n'
    '    print("Offline package installation finished.")\n'
    'else:\n'
    '    print("USE_PRETRAINED=1: skipping installation.")\n'
))

cells.append(code(
    'if TRAIN_ON_KAGGLE:\n'
    '    import torch\n'
    '    import kagglehub\n'
    '    from unsloth import FastLanguageModel\n'
    '\n'
    '    MAX_SEQ_LEN = 8192\n'
    '    MODEL_PATH = kagglehub.model_download("metric/nemotron-3-nano-30b-a3b-bf16/transformers/default")\n'
    '    print(f"Model path: {MODEL_PATH}")\n'
    '\n'
    '    model, tokenizer = FastLanguageModel.from_pretrained(\n'
    '        model_name=MODEL_PATH,\n'
    '        max_seq_length=MAX_SEQ_LEN,\n'
    '        load_in_4bit=False,\n'
    '        load_in_8bit=False,\n'
    '        full_finetuning=False,\n'
    '        trust_remote_code=True,\n'
    '        unsloth_force_compile=False,\n'
    '        attn_implementation="eager",\n'
    '        dtype=torch.bfloat16,\n'
    '    )\n'
    '    if tokenizer.pad_token is None:\n'
    '        tokenizer.pad_token = tokenizer.eos_token\n'
    '    print("Base model loaded with Unsloth.")\n'
    'else:\n'
    '    print("USE_PRETRAINED=1: skipping base model load.")\n'
))

cells.append(md("## LoRA Wrap (warm-start optional)"))

cells.append(code(
    'if TRAIN_ON_KAGGLE:\n'
    '    from unsloth import FastLanguageModel\n'
    '\n'
    '    # ------------------------------------------------------------------\n'
    '    # LoRA config — same as v9-1 GRPO (RSLoRA, rank 32, no lm_head)\n'
    '    # ------------------------------------------------------------------\n'
    '    LORA_RANK = 32\n'
    '    LORA_ALPHA = 64\n'
    '    LORA_DROPOUT = 0.0  # ES has its own stochastic search; no need for dropout\n'
    '\n'
    '    target_modules = [\n'
    '        # Attention\n'
    '        "q_proj", "k_proj", "v_proj", "o_proj",\n'
    '        "in_proj", "out_proj",\n'
    '        # MLP / MoE\n'
    '        "gate_proj", "up_proj", "down_proj",\n'
    '        # Mamba SSM\n'
    '        "x_proj", "dt_proj",\n'
    '        # lm_head intentionally excluded (boxed format stability)\n'
    '    ]\n'
    '\n'
    '    model = FastLanguageModel.get_peft_model(\n'
    '        model,\n'
    '        r=LORA_RANK,\n'
    '        lora_alpha=LORA_ALPHA,\n'
    '        lora_dropout=LORA_DROPOUT,\n'
    '        target_modules=target_modules,\n'
    '        bias="none",\n'
    '        use_gradient_checkpointing=False,  # ES does no backprop\n'
    '        random_state=42,\n'
    '        use_rslora=True,\n'
    '    )\n'
    '    model.print_trainable_parameters()\n'
    '\n'
    '    # ------------------------------------------------------------------\n'
    '    # Optional warm-start: overwrite the freshly-initialized LoRA weights\n'
    '    # with the SFT adapter from disk. We do this *after* get_peft_model\n'
    '    # so the PEFT structure (target modules / rank) already matches.\n'
    '    # ------------------------------------------------------------------\n'
    '    if INIT_FROM_SFT_ADAPTER:\n'
    '        from safetensors.torch import load_file\n'
    '        import os\n'
    '\n'
    '        adapter_file = os.path.join(SFT_ADAPTER_PATH, "adapter_model.safetensors")\n'
    '        if not os.path.exists(adapter_file):\n'
    '            raise FileNotFoundError(f"Missing SFT adapter at {adapter_file}")\n'
    '\n'
    '        print(f"Warm-starting LoRA from {adapter_file}")\n'
    '        sd = load_file(adapter_file)\n'
    '        # PEFT exposes adapter weights under names like\n'
    '        #   base_model.model.<layer>.lora_A.default.weight\n'
    '        # Sometimes safetensors files store them without the ".default" suffix.\n'
    '        model_sd = model.state_dict()\n'
    '        renamed = {}\n'
    '        for k, v in sd.items():\n'
    '            if k in model_sd:\n'
    '                renamed[k] = v\n'
    '            else:\n'
    '                # Try inserting ".default" before ".weight"\n'
    '                for adapt_name in ("lora_A", "lora_B"):\n'
    '                    needle = f"{adapt_name}.weight"\n'
    '                    if needle in k:\n'
    '                        cand = k.replace(needle, f"{adapt_name}.default.weight")\n'
    '                        if cand in model_sd:\n'
    '                            renamed[cand] = v\n'
    '                            break\n'
    '        missing, unexpected = model.load_state_dict(renamed, strict=False)\n'
    '        lora_missing = [m for m in missing if "lora_" in m]\n'
    '        lora_unexpected = [u for u in unexpected if "lora_" in u]\n'
    '        print(f"Warm-start: matched {len(renamed)} tensors. "\n'
    '              f"LoRA-missing={len(lora_missing)}, LoRA-unexpected={len(lora_unexpected)}")\n'
    '        if lora_missing:\n'
    '            print("First 5 missing LoRA params:", lora_missing[:5])\n'
    '    else:\n'
    '        print("Cold start: LoRA initialised from scratch (kaiming A, zero B).")\n'
    'else:\n'
    '    print("USE_PRETRAINED=1: skipping LoRA wrap.")\n'
))

cells.append(md(
    "## Reward Functions (reused from v9-1 GRPO)\n"
    "\n"
    "Multi-component reward: correctness (2.0) + format (1.0) + length (0.3) + repetition guard.\n"
    "Max ≈ 3.4. ES uses **mean** reward over the prompt-batch as the per-perturbation fitness.\n"
))

cells.append(code(
    'if TRAIN_ON_KAGGLE:\n'
    '    import re\n'
    '\n'
    '    def _extract_boxed(text: str):\n'
    '        """Extract content from last \\\\boxed{} with nested-brace support."""\n'
    '        pos = text.rfind(r"\\boxed{")\n'
    '        if pos == -1:\n'
    '            return None\n'
    '        start = pos + len(r"\\boxed{")\n'
    '        depth, i = 1, start\n'
    '        while i < len(text) and depth > 0:\n'
    '            if text[i] == "{":\n'
    '                depth += 1\n'
    '            elif text[i] == "}":\n'
    '                depth -= 1\n'
    '            i += 1\n'
    '        return text[start : i - 1].strip() if depth == 0 else None\n'
    '\n'
    '    def _normalize(ans):\n'
    '        if not ans:\n'
    '            return ""\n'
    '        ans = ans.strip()\n'
    '        for tok in (r"\\\\,", r"\\,", r"\\\\!", r"\\!", r"\\\\ ", r"\\ ", r"\\text{", "}"):\n'
    '            ans = ans.replace(tok, "")\n'
    '        try:\n'
    '            val = float(ans.replace(",", ""))\n'
    '            if val == int(val) and abs(val) < 1e15:\n'
    '                return str(int(val))\n'
    '            return f"{val:.8g}"\n'
    '        except (ValueError, OverflowError):\n'
    '            pass\n'
    '        return ans.lower().replace(" ", "")\n'
    '\n'
    '    def _is_correct(pred, gold):\n'
    '        if pred is None:\n'
    '            return False\n'
    '        p, g = _normalize(pred), _normalize(str(gold))\n'
    '        if p == g:\n'
    '            return True\n'
    '        try:\n'
    '            pv, gv = float(p.replace(",", "")), float(g.replace(",", ""))\n'
    '            return abs(pv - gv) < 1e-6 or (gv != 0 and abs(pv - gv) / abs(gv) < 1e-5)\n'
    '        except (ValueError, OverflowError):\n'
    '            pass\n'
    '        return False\n'
    '\n'
    '    def reward_correctness(completions, answer, **kwargs):\n'
    '        return [\n'
    '            2.0 if _is_correct(_extract_boxed(c), str(a)) else 0.0\n'
    '            for c, a in zip(completions, answer)\n'
    '        ]\n'
    '\n'
    '    def reward_format(completions, **kwargs):\n'
    '        rewards = []\n'
    '        for c in completions:\n'
    '            score = 0.0\n'
    '            has_open = "<think>" in c\n'
    '            has_close = "</think>" in c\n'
    '            has_boxed = r"\\boxed{" in c\n'
    '            extracted = _extract_boxed(c)\n'
    '            if has_open and has_close:\n'
    '                score += 0.3\n'
    '                think_end = c.rfind("</think>")\n'
    '                boxed_pos = c.rfind(r"\\boxed{")\n'
    '                if boxed_pos > think_end > 0:\n'
    '                    score += 0.1\n'
    '            if has_boxed:\n'
    '                score += 0.4\n'
    '            if extracted is not None and len(extracted) > 0:\n'
    '                score += 0.2\n'
    '            rewards.append(min(score, 1.0))\n'
    '        return rewards\n'
    '\n'
    '    def reward_reasoning_length(completions, **kwargs):\n'
    '        RAMP_TO, PLATEAU_TO, DECAY_TO = 2000, 5500, 8000\n'
    '        rewards = []\n'
    '        for c in completions:\n'
    '            m = re.search(r"<think>(.*?)</think>", c, re.DOTALL)\n'
    '            n = len(m.group(1)) if m else 0\n'
    '            if n <= RAMP_TO:\n'
    '                score = 0.3 * n / RAMP_TO\n'
    '            elif n <= PLATEAU_TO:\n'
    '                score = 0.3\n'
    '            elif n <= DECAY_TO:\n'
    '                score = 0.3 * (DECAY_TO - n) / (DECAY_TO - PLATEAU_TO)\n'
    '            else:\n'
    '                score = 0.0\n'
    '            rewards.append(score)\n'
    '        return rewards\n'
    '\n'
    '    def reward_no_repetition(completions, **kwargs):\n'
    '        rewards = []\n'
    '        for c in completions:\n'
    '            words = c.split()\n'
    '            if len(words) < 30:\n'
    '                rewards.append(0.0)\n'
    '                continue\n'
    '            tail = words[-min(len(words), 200):]\n'
    '            ngrams = [tuple(tail[i : i + 6]) for i in range(len(tail) - 5)]\n'
    '            if not ngrams:\n'
    '                rewards.append(0.0)\n'
    '                continue\n'
    '            div = len(set(ngrams)) / len(ngrams)\n'
    '            if div >= 0.85:\n'
    '                rewards.append(0.1)\n'
    '            elif div >= 0.65:\n'
    '                rewards.append(0.0)\n'
    '            elif div >= 0.45:\n'
    '                rewards.append(-0.15)\n'
    '            else:\n'
    '                rewards.append(-0.3)\n'
    '        return rewards\n'
    '\n'
    '    def reward_combined(completions, answer, **kwargs):\n'
    '        cor = reward_correctness(completions, answer, **kwargs)\n'
    '        fmt = reward_format(completions, **kwargs)\n'
    '        lng = reward_reasoning_length(completions, **kwargs)\n'
    '        rep = reward_no_repetition(completions, **kwargs)\n'
    '        return [c + f + l + r for c, f, l, r in zip(cor, fmt, lng, rep)]\n'
    '\n'
    '    print("Reward functions ready (correctness 2.0 + format 1.0 + length 0.3 + rep ±).")\n'
    'else:\n'
    '    print("USE_PRETRAINED=1: skipping reward definitions.")\n'
))

cells.append(md("## Dataset"))

cells.append(code(
    'if TRAIN_ON_KAGGLE:\n'
    '    import pandas as pd\n'
    '\n'
    '    SEED = 42\n'
    '    PROMPT_SUFFIX = "\\nPlease put your final answer inside `\\\\boxed{}`. For example: `\\\\boxed{your answer}`"\n'
    '    SYSTEM_PROMPT = (\n'
    '        "You are an expert mathematics assistant. "\n'
    '        "Think carefully step by step inside <think>...</think> tags, "\n'
    '        "then give your final answer inside \\\\boxed{}."\n'
    '    )\n'
    '    DATASET_PATH = "/kaggle/input/datasets/dgxchen/nemotron-cot-tong/problem_ids_matched.csv"\n'
    '\n'
    '    df = pd.read_csv(DATASET_PATH)\n'
    '    df = df.dropna(subset=["answer", "prompt"]).reset_index(drop=True)\n'
    '    df = df.sample(frac=1, random_state=SEED).reset_index(drop=True)\n'
    '    print(f"Dataset: {len(df)} rows")\n'
    '\n'
    '    # ES needs prompt+answer pairs (answer used for reward).\n'
    '    es_records = []\n'
    '    for _, row in df.iterrows():\n'
    '        es_records.append({\n'
    '            "messages": [\n'
    '                {"role": "system", "content": SYSTEM_PROMPT},\n'
    '                {"role": "user", "content": str(row["prompt"]) + PROMPT_SUFFIX},\n'
    '            ],\n'
    '            "answer": str(row["answer"]),\n'
    '        })\n'
    '    print(f"ES records: {len(es_records)}")\n'
    'else:\n'
    '    print("USE_PRETRAINED=1: skipping dataset load.")\n'
))

cells.append(md(
    "## Mode A: Evolution Strategies Training Loop\n"
    "\n"
    "Vanilla ES per arXiv:2509.24372:\n"
    "\n"
    "```\n"
    "for step in 1..NUM_STEPS:\n"
    "    sample batch B of (prompt, answer)\n"
    "    sample N seeds  →  perturbations ε_i ~ N(0, I) on LoRA params\n"
    "    if ANTITHETIC:  pair each ε_i with −ε_i  (N must be even)\n"
    "    for i in 1..N:\n"
    "        θ ← θ + σ·ε_i\n"
    "        R_i = mean(reward_combined(generate(B), answers))\n"
    "        θ ← θ − σ·ε_i\n"
    "    r_norm = centered_rank(R)   ∈ [−0.5, +0.5]\n"
    "    θ ← θ + (α / (N·σ)) · Σ_i r_norm_i · ε_i\n"
    "```\n"
    "\n"
    "Seed replay avoids storing N copies of the noise tensors — we re-sample\n"
    "from each seed both when applying ±σ·ε_i and when accumulating the update.\n"
    "\n"
    "**EGGROLL hook**: if `ES_VARIANT == \"eggroll\"`, replace each iid noise on a\n"
    "weight matrix W with a rank-1 product `u · vᵀ` drawn from the same seed.\n"
    "Vanilla is the default per user choice.\n"
))

cells.append(code(
    'if TRAIN_ON_KAGGLE:\n'
    '    import os\n'
    '    os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"\n'
    '\n'
    '    import gc, time, math, random\n'
    '    import numpy as np\n'
    '    import torch\n'
    '\n'
    '    # =================================================================\n'
    '    # ES HYPERPARAMETERS\n'
    '    # =================================================================\n'
    '    ES_VARIANT       = "vanilla"   # "vanilla" or "eggroll" (rank-1 low-rank)\n'
    '    NUM_STEPS        = 200         # ES iterations; each ≈ 2–5 min on Kaggle\n'
    '    POPULATION_SIZE  = 8           # must be even when ANTITHETIC=True\n'
    '    ANTITHETIC       = True        # ±ε pair → halves effective forward passes\n'
    '    SIGMA            = 1e-3        # perturbation scale (paper default)\n'
    '    ALPHA            = 5e-4        # learning rate (paper default)\n'
    '    PROMPTS_PER_STEP = 4           # B: batch of prompts per perturbation\n'
    '    MAX_NEW_TOKENS   = 1024        # cap completions; reduce if OOM\n'
    '    GEN_TEMPERATURE  = 0.7\n'
    '    GEN_TOP_P        = 0.9\n'
    '    LOG_EVERY        = 1           # print metrics every N steps\n'
    '    SAVE_EVERY       = 50          # checkpoint LoRA every N steps\n'
    '    ADAPTER_DIR      = "/kaggle/working/sft_adapter"\n'
    '    CHECKPOINT_DIR   = "/kaggle/working/es_checkpoints"\n'
    '    EGGROLL_RANK     = 1           # used only when ES_VARIANT="eggroll"\n'
    '\n'
    '    assert (not ANTITHETIC) or POPULATION_SIZE % 2 == 0, \\\n'
    '        "POPULATION_SIZE must be even when ANTITHETIC=True"\n'
    '\n'
    '    os.makedirs(ADAPTER_DIR, exist_ok=True)\n'
    '    os.makedirs(CHECKPOINT_DIR, exist_ok=True)\n'
    '\n'
    '    # =================================================================\n'
    '    # Collect trainable LoRA tensors only\n'
    '    # =================================================================\n'
    '    lora_params = []  # list[(name, tensor)]\n'
    '    for n, p in model.named_parameters():\n'
    '        if p.requires_grad and ("lora_A" in n or "lora_B" in n):\n'
    '            # ES is gradient-free — freeze autograd to save memory.\n'
    '            p.requires_grad = False\n'
    '            lora_params.append((n, p))\n'
    '    total = sum(p.numel() for _, p in lora_params)\n'
    '    print(f"LoRA params under ES: {len(lora_params)} tensors, {total/1e6:.2f} M elements")\n'
    '\n'
    '    # =================================================================\n'
    '    # Noise generation — seed-replay keeps mem O(1) in pop size\n'
    '    # =================================================================\n'
    '    def _maybe_lowrank(noise_full, shape, gen, rank):\n'
    '        """Replace iid noise on a 2-D weight with a rank-`r` u·v^T."""\n'
    '        if len(shape) != 2 or rank >= min(shape):\n'
    '            return noise_full\n'
    '        out, inp = shape\n'
    '        u = torch.randn(out, rank, generator=gen, device=noise_full.device, dtype=noise_full.dtype)\n'
    '        v = torch.randn(rank, inp, generator=gen, device=noise_full.device, dtype=noise_full.dtype)\n'
    '        # Normalize so Var(u·v^T) ≈ 1 element-wise:\n'
    '        # Var(<u_row, v_col>) = sum_k Var(u_ik) Var(v_kj) = rank.\n'
    '        return (u @ v) / math.sqrt(rank)\n'
    '\n'
    '    def apply_perturbation(seed: int, sign: float):\n'
    '        """In-place θ ← θ + sign·σ·ε(seed). Restores deterministically via sign=−1."""\n'
    '        gen = torch.Generator(device=lora_params[0][1].device)\n'
    '        gen.manual_seed(int(seed))\n'
    '        for _, p in lora_params:\n'
    '            noise = torch.randn(p.shape, generator=gen, device=p.device, dtype=p.dtype)\n'
    '            if ES_VARIANT == "eggroll":\n'
    '                noise = _maybe_lowrank(noise, tuple(p.shape), gen, EGGROLL_RANK)\n'
    '            p.data.add_(noise, alpha=float(sign) * SIGMA)\n'
    '            del noise\n'
    '\n'
    '    def accumulate_update(seed: int, weight: float, update_buffers: list):\n'
    '        """update_buffers[i] += weight · ε_i(seed)  (no σ factor here)."""\n'
    '        gen = torch.Generator(device=lora_params[0][1].device)\n'
    '        gen.manual_seed(int(seed))\n'
    '        for (_, p), buf in zip(lora_params, update_buffers):\n'
    '            noise = torch.randn(p.shape, generator=gen, device=p.device, dtype=p.dtype)\n'
    '            if ES_VARIANT == "eggroll":\n'
    '                noise = _maybe_lowrank(noise, tuple(p.shape), gen, EGGROLL_RANK)\n'
    '            buf.add_(noise, alpha=float(weight))\n'
    '            del noise\n'
    '\n'
    '    # =================================================================\n'
    '    # Batched generation\n'
    '    # =================================================================\n'
    '    def render_prompts(records):\n'
    '        texts = []\n'
    '        for r in records:\n'
    '            try:\n'
    '                t = tokenizer.apply_chat_template(\n'
    '                    r["messages"], tokenize=False, add_generation_prompt=True, enable_thinking=True\n'
    '                )\n'
    '            except TypeError:\n'
    '                t = tokenizer.apply_chat_template(\n'
    '                    r["messages"], tokenize=False, add_generation_prompt=True\n'
    '                )\n'
    '            texts.append(t)\n'
    '        return texts\n'
    '\n'
    '    @torch.no_grad()\n'
    '    def generate_completions(prompt_texts):\n'
    '        model.eval()\n'
    '        enc = tokenizer(\n'
    '            prompt_texts,\n'
    '            return_tensors="pt",\n'
    '            padding=True,\n'
    '            truncation=True,\n'
    '            max_length=MAX_SEQ_LEN - MAX_NEW_TOKENS,\n'
    '        ).to(model.device)\n'
    '        out = model.generate(\n'
    '            **enc,\n'
    '            max_new_tokens=MAX_NEW_TOKENS,\n'
    '            do_sample=True,\n'
    '            temperature=GEN_TEMPERATURE,\n'
    '            top_p=GEN_TOP_P,\n'
    '            pad_token_id=tokenizer.pad_token_id,\n'
    '            use_cache=True,\n'
    '        )\n'
    '        gen_only = out[:, enc.input_ids.shape[1]:]\n'
    '        completions = tokenizer.batch_decode(gen_only, skip_special_tokens=True)\n'
    '        del enc, out, gen_only\n'
    '        return completions\n'
    '\n'
    '    # =================================================================\n'
    '    # Centered-rank transform (robust to outlier rewards)\n'
    '    # =================================================================\n'
    '    def centered_ranks(rewards):\n'
    '        arr = np.asarray(rewards, dtype=np.float64)\n'
    '        order = arr.argsort()\n'
    '        ranks = np.empty_like(order)\n'
    '        ranks[order] = np.arange(len(arr))\n'
    '        if len(arr) <= 1:\n'
    '            return np.zeros_like(arr)\n'
    '        return ranks / (len(arr) - 1) - 0.5\n'
    '\n'
    '    # =================================================================\n'
    '    # Build seed list for one ES step (antithetic pairing)\n'
    '    # =================================================================\n'
    '    def build_seed_pairs(rng, n, antithetic):\n'
    '        """Return list[(seed, sign)] of length n. For antithetic, half use sign=+1, half sign=−1 with paired seeds."""\n'
    '        if antithetic:\n'
    '            base = [int(rng.randint(0, 2**31 - 1)) for _ in range(n // 2)]\n'
    '            pairs = []\n'
    '            for s in base:\n'
    '                pairs.append((s, +1.0))\n'
    '                pairs.append((s, -1.0))\n'
    '            return pairs\n'
    '        return [(int(rng.randint(0, 2**31 - 1)), +1.0) for _ in range(n)]\n'
    '\n'
    '    print("ES training utilities ready.")\n'
    '    print(f"  Variant={ES_VARIANT}, Pop={POPULATION_SIZE}, Antithetic={ANTITHETIC}")\n'
    '    print(f"  sigma={SIGMA}, alpha={ALPHA}, prompts/step={PROMPTS_PER_STEP}")\n'
    'else:\n'
    '    print("USE_PRETRAINED=1: skipping ES utilities.")\n'
))

cells.append(code(
    'if TRAIN_ON_KAGGLE:\n'
    '    # =================================================================\n'
    '    # MAIN ES TRAINING LOOP\n'
    '    # =================================================================\n'
    '    torch.cuda.empty_cache()\n'
    '    gc.collect()\n'
    '\n'
    '    py_rng = random.Random(SEED)\n'
    '    history = []\n'
    '    t_start = time.time()\n'
    '\n'
    '    # Pre-allocate update buffers once; reuse each step (zero in place).\n'
    '    update_buffers = [torch.zeros_like(p) for _, p in lora_params]\n'
    '\n'
    '    print(f"\\n{\"=\"*60}\\n  ES TRAINING — {NUM_STEPS} steps\\n{\"=\"*60}\")\n'
    '\n'
    '    for step in range(1, NUM_STEPS + 1):\n'
    '        step_t0 = time.time()\n'
    '\n'
    '        # Sample a fresh batch of prompts for this step.\n'
    '        batch_idx = [py_rng.randrange(len(es_records)) for _ in range(PROMPTS_PER_STEP)]\n'
    '        batch = [es_records[i] for i in batch_idx]\n'
    '        prompt_texts = render_prompts(batch)\n'
    '        gold_answers = [r["answer"] for r in batch]\n'
    '\n'
    '        # Build the population of seeds for this step.\n'
    '        seed_signs = build_seed_pairs(py_rng, POPULATION_SIZE, ANTITHETIC)\n'
    '\n'
    '        # ---- Evaluate every population member ----\n'
    '        rewards = []\n'
    '        for i, (seed, sign) in enumerate(seed_signs):\n'
    '            apply_perturbation(seed, sign)\n'
    '            try:\n'
    '                completions = generate_completions(prompt_texts)\n'
    '                r_each = reward_combined(completions, gold_answers)\n'
    '                rewards.append(float(np.mean(r_each)))\n'
    '            finally:\n'
    '                # Always undo the perturbation, even if generation failed.\n'
    '                apply_perturbation(seed, -sign)\n'
    '\n'
    '        # Free per-step intermediates.\n'
    '        torch.cuda.empty_cache()\n'
    '\n'
    '        # ---- Centered-rank normalize then apply update ----\n'
    '        rn = centered_ranks(rewards)\n'
    '\n'
    '        for buf in update_buffers:\n'
    '            buf.zero_()\n'
    '\n'
    '        for (seed, sign), r_norm in zip(seed_signs, rn):\n'
    '            # weight = r_norm · sign  (sign folds antithetic mirror back in)\n'
    '            accumulate_update(seed, float(r_norm * sign), update_buffers)\n'
    '\n'
    '        # θ ← θ + (α / (N·σ)) · Σ_i r_norm_i · ε_i\n'
    '        scale = ALPHA / (POPULATION_SIZE * SIGMA)\n'
    '        with torch.no_grad():\n'
    '            for (_, p), buf in zip(lora_params, update_buffers):\n'
    '                p.data.add_(buf, alpha=scale)\n'
    '\n'
    '        dt = time.time() - step_t0\n'
    '        history.append({\n'
    '            "step": step,\n'
    '            "reward_mean": float(np.mean(rewards)),\n'
    '            "reward_max": float(np.max(rewards)),\n'
    '            "reward_min": float(np.min(rewards)),\n'
    '            "reward_std": float(np.std(rewards)),\n'
    '            "time_s": dt,\n'
    '        })\n'
    '\n'
    '        if step % LOG_EVERY == 0:\n'
    '            elapsed = (time.time() - t_start) / 60.0\n'
    '            print(\n'
    '                f"[step {step:4d}/{NUM_STEPS}] "\n'
    '                f"R mean={np.mean(rewards):.3f}  max={np.max(rewards):.3f}  std={np.std(rewards):.3f}  "\n'
    '                f"step_time={dt:.1f}s  total={elapsed:.1f}m"\n'
    '            )\n'
    '\n'
    '        if step % SAVE_EVERY == 0:\n'
    '            ckpt = os.path.join(CHECKPOINT_DIR, f"step_{step:04d}")\n'
    '            model.save_pretrained(ckpt)\n'
    '            print(f"  ↳ checkpoint saved: {ckpt}")\n'
    '\n'
    '    elapsed_min = (time.time() - t_start) / 60.0\n'
    '    print(f"\\nES training done in {elapsed_min:.1f} min over {NUM_STEPS} steps.")\n'
    '\n'
    '    # =================================================================\n'
    '    # Final save\n'
    '    # =================================================================\n'
    '    model.save_pretrained(ADAPTER_DIR)\n'
    '    tokenizer.save_pretrained(ADAPTER_DIR)\n'
    '    print(f"Final adapter saved to {ADAPTER_DIR}")\n'
    '\n'
    '    import json as _json\n'
    '    with open("/kaggle/working/es_history.json", "w") as f:\n'
    '        _json.dump(history, f, indent=2)\n'
    '    print("History dumped to /kaggle/working/es_history.json")\n'
    'else:\n'
    '    print("USE_PRETRAINED=1: skipping ES training.")\n'
))

cells.append(md("## Mode B: Load Pre-trained LoRA"))

cells.append(code(
    'if USE_PRETRAINED:\n'
    '    import os\n'
    '\n'
    '    SRC_ADAPTER_DIR = PRETRAINED_ADAPTER_DATASET_PATH\n'
    '    required_files = ["adapter_config.json", "adapter_model.safetensors"]\n'
    '\n'
    '    print("Using pre-trained adapter from:", SRC_ADAPTER_DIR)\n'
    '    for fname in required_files:\n'
    '        fpath = os.path.join(SRC_ADAPTER_DIR, fname)\n'
    '        if not os.path.exists(fpath):\n'
    '            raise FileNotFoundError(f"Missing required adapter file: {fpath}")\n'
    '        print(f"  {fname}: {os.path.getsize(fpath)/1024/1024:.1f} MB")\n'
    'else:\n'
    '    print("TRAIN_ON_KAGGLE=1: pretrained adapter path check skipped.")\n'
))

cells.append(md("## Create submission.zip"))

cells.append(code(
    'import json, os, shutil, zipfile\n'
    '\n'
    'OUTPUT_DIR = "/kaggle/working"\n'
    'SUBMISSION_ADAPTER_DIR = os.path.join(OUTPUT_DIR, "submission_adapter")\n'
    'os.makedirs(SUBMISSION_ADAPTER_DIR, exist_ok=True)\n'
    '\n'
    'required_files = ["adapter_config.json", "adapter_model.safetensors"]\n'
    '\n'
    'if TRAIN_ON_KAGGLE:\n'
    '    src_adapter_dir = "/kaggle/working/sft_adapter"\n'
    '    print("Packaging ES-trained adapter from:", src_adapter_dir)\n'
    'else:\n'
    '    src_adapter_dir = PRETRAINED_ADAPTER_DATASET_PATH\n'
    '    print("Packaging pre-trained adapter directly from:", src_adapter_dir)\n'
    '\n'
    'for fname in required_files:\n'
    '    src = os.path.join(src_adapter_dir, fname)\n'
    '    dst = os.path.join(SUBMISSION_ADAPTER_DIR, fname)\n'
    '    if not os.path.exists(src):\n'
    '        raise FileNotFoundError(f"Missing required adapter file: {src}")\n'
    '    shutil.copy2(src, dst)\n'
    '    print(f"Copied {fname} ({os.path.getsize(dst)/1024/1024:.1f} MB)")\n'
    '\n'
    'config_path = os.path.join(SUBMISSION_ADAPTER_DIR, "adapter_config.json")\n'
    'with open(config_path, "r") as f:\n'
    '    cfg = json.load(f)\n'
    '\n'
    'cfg["base_model_name_or_path"] = BASE_MODEL_NAME\n'
    'cfg["inference_mode"] = True\n'
    'cfg["lora_dropout"] = 0.0\n'
    '\n'
    'with open(config_path, "w") as f:\n'
    '    json.dump(cfg, f, indent=2)\n'
    '\n'
    'zip_path = os.path.join(OUTPUT_DIR, "submission.zip")\n'
    'with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:\n'
    '    for fname in required_files:\n'
    '        fpath = os.path.join(SUBMISSION_ADAPTER_DIR, fname)\n'
    '        zf.write(fpath, fname)\n'
    '        print(f"  Added {fname}")\n'
    '\n'
    'zip_sz = os.path.getsize(zip_path) / 1024 / 1024\n'
    'print(f"\\nsubmission.zip: {zip_sz:.1f} MB")\n'
    'print("Done! Ready to submit.")\n'
))

# =============================================================================
# Assemble notebook
# =============================================================================

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.11",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NB_PATH.write_text(json.dumps(notebook, indent=1))
print(f"Wrote {NB_PATH}")